{{ if .Values.version.beta }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Chart.Name }}-autoscaler-beta"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ .Chart.Name }}-beta"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "{{ .Chart.Name }}-deployment-beta"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
{{ end }}