{{ if .Values.version.beta }}
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "{{ .Chart.Name }}-deployment-beta"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ .Chart.Name }}-beta"
spec:
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}-beta"
  template:
    metadata:
      labels:
        environment: "{{ .Values.environment }}"
        app: "{{ .Chart.Name }}-beta"
    spec:
      imagePullSecrets:
      - name: jfrogregistrykey
      containers:
      - name: "{{ .Chart.Name }}"
        image: "{{ .Values.image }}{{ .Values.version.beta }}"
        resources:
          requests:
            memory: "{{ .Values.memory_request }}"
            cpu: "{{ .Values.cpu_request }}"
          limits:
            memory: "{{ .Values.memory_limit }}"
            cpu: "{{ .Values.cpu_limit }}"
        env:
        - name: APP_VERSION
          value: "{{ .Values.version.beta }}"
        - name: SPRING_PROFILES_ACTIVE
          value: "{{ .Values.environment }}"
        - name: REDIS_PASSWORD
          value: "{{ .Values.redis.password }}"
        - name: REDIS_PORT
          value: "{{ .Values.redis.port }}"
        - name: REDIS_ARGS
          value: "{{ .Values.redis.args }}"
{{ end }}