apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: redis-pv-claim
  namespace: ani
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 9Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: redis-config-claim
  namespace: ani
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi