apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  namespace: nginx
  labels:
    name: nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: aws-alb
  namespace: aws-alb
  labels:
    name: aws-alb