apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Chart.Name }}-autoscaler"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ .Chart.Name }}"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "{{ .Chart.Name }}-deployment"
    apiVersion: "apps/v1"
  minReplicas: {{ .Values.replicas.min }}
  maxReplicas: {{ .Values.replicas.max }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70