apiVersion: "v1"
kind: "Service"
metadata:
  name: "{{ .Chart.Name }}-service"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Chart.Name }}"
spec:
  ports:
  - name: https-{{ .Chart.Name }}
    port: {{ .Values.port.external }}
    targetPort: {{ .Values.port.internal }}
  selector:
    app: "{{ .Chart.Name }}"
